package net.lambdaserve.http

enum Method:
  case GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS, TRACE, CONNECT

enum Version:
  case HTTP_1_0, HTTP_1_1, HTTP_2_0

enum Status(val code: Int):
  case Continue                    extends Status(100)
  case SwitchingProtocols          extends Status(101)
  case Processing                  extends Status(102)
  case EarlyHints                  extends Status(103)
  case OK                          extends Status(200)
  case Created                     extends Status(201)
  case Accepted                    extends Status(202)
  case NonAuthoritativeInformation extends Status(203)
  case NoContent                   extends Status(204)
  case ResetContent                extends Status(205)
  case PartialContent              extends Status(206)
  case MultiStatus                 extends Status(207)
  case AlreadyReported             extends Status(208)
  case IMUsed                      extends Status(226)
  case MultipleChoices             extends Status(300)
  case MovedPermanently            extends Status(301)
  case Found                       extends Status(302)
  case SeeOther                    extends Status(303)
  case NotModified                 extends Status(304)
  case UseProxy                    extends Status(305)
  case TemporaryRedirect           extends Status(307)
  case PermanentRedirect           extends Status(308)
  case BadRequest                  extends Status(400)
  case Unauthorized                extends Status(401)
  case PaymentRequired             extends Status(402)
  case Forbidden                   extends Status(403)
  case NotFound                    extends Status(404)
  case MethodNotAllowed            extends Status(405)
  case NotAcceptable               extends Status(406)
  case ProxyAuthenticationRequired extends Status(407)
  case RequestTimeout              extends Status(408)
  case Conflict                    extends Status(409)
  case Gone                        extends Status(410)
  case LengthRequired              extends Status(411)
  case PreconditionFailed          extends Status(412)
  case PayloadTooLarge             extends Status(413)
  case URITooLong                  extends Status(414)
  case UnsupportedMediaType        extends Status(415)
  case RangeNotSatisfiable         extends Status(416)
  case ExpectationFailed           extends Status(417)
  case ImATeapot                   extends Status(418)
  case MisdirectedRequest          extends Status(421)
  case UnprocessableEntity         extends Status(422)
  case Locked                      extends Status(423)
  case FailedDependency            extends Status(424)
  case TooEarly                    extends Status(425)
  case UpgradeRequired             extends Status(426)
  case PreconditionRequired        extends Status(428)
  case TooManyRequests             extends Status(429)
  case RequestHeaderFieldsTooLarge extends Status(431)
  case UnavailableForLegalReasons  extends Status(451)
  case InternalServerError         extends Status(500)
  case NotImplemented              extends Status(501)
  case BadGateway                  extends Status(502)

enum Header(val name: String):
  case Accept         extends Header("Accept")
  case AcceptCharset  extends Header("Accept-Charset")
  case AcceptEncoding extends Header("Accept-Encoding")
  case AcceptLanguage extends Header("Accept-Language")
  case AcceptRanges   extends Header("Accept-Ranges")
  case AccessControlAllowCredentials
      extends Header("Access-Control-Allow-Credentials")
  case AccessControlAllowHeaders extends Header("Access-Control-Allow-Headers")
  case AccessControlAllowMethods extends Header("Access-Control-Allow-Methods")
  case AccessControlAllowOrigin  extends Header("Access-Control-Allow-Origin")
  case AccessControlExposeHeaders
      extends Header("Access-Control-Expose-Headers")
  case AccessControlMaxAge extends Header("Access-Control-Max-Age")
  case AccessControlRequestHeaders
      extends Header("Access-Control-Request-Headers")
  case AccessControlRequestMethod
      extends Header("Access-Control-Request-Method")
  case Age                     extends Header("Age")
  case Allow                   extends Header("Allow")
  case Authorization           extends Header("Authorization")
  case CacheControl            extends Header("Cache-Control")
  case Connection              extends Header("Connection")
  case ContentDisposition      extends Header("Content-Disposition")
  case ContentEncoding         extends Header("Content-Encoding")
  case ContentLanguage         extends Header("Content-Language")
  case ContentLength           extends Header("Content-Length")
  case ContentLocation         extends Header("Content-Location")
  case ContentRange            extends Header("Content-Range")
  case ContentType             extends Header("Content-Type")
  case Cookie                  extends Header("Cookie")
  case Date                    extends Header("Date")
  case ETag                    extends Header("ETag")
  case Expect                  extends Header("Expect")
  case Expires                 extends Header("Expires")
  case Forwarded               extends Header("Forwarded")
  case From                    extends Header("From")
  case Host                    extends Header("Host")
  case IfMatch                 extends Header("If-Match")
  case IfModifiedSince         extends Header("If-Modified-Since")
  case IfNoneMatch             extends Header("If-None-Match")
  case IfRange                 extends Header("If-Range")
  case IfUnmodifiedSince       extends Header("If-Unmodified-Since")
  case LastModified            extends Header("Last-Modified")
  case Link                    extends Header("Link")
  case Location                extends Header("Location")
  case MaxForwards             extends Header("Max-Forwards")
  case Origin                  extends Header("Origin")
  case Pragma                  extends Header("Pragma")
  case ProxyAuthenticate       extends Header("Proxy-Authenticate")
  case ProxyAuthorization      extends Header("Proxy-Authorization")
  case Range                   extends Header("Range")
  case Referer                 extends Header("Referer")
  case RetryAfter              extends Header("Retry-After")
  case Server                  extends Header("Server")
  case SetCookie               extends Header("Set-Cookie")
  case StrictTransportSecurity extends Header("Strict-Transport-Security")
  case TE                      extends Header("TE")
  case Trailer                 extends Header("Trailer")
  case TransferEncoding        extends Header("Transfer-Encoding")
  case Upgrade                 extends Header("Upgrade")
  case UserAgent               extends Header("User-Agent")
  case Vary                    extends Header("Vary")
  case Via                     extends Header("Via")
  case Warning                 extends Header("Warning")
  case WWWAuthenticate         extends Header("WWW-Authenticate")
